from typing import List, Set, cast

import jubilant
import pytest
import requests
from jubilant import Juju
from tenacity import retry, stop_after_attempt, wait_fixed

from tests.integration.helpers import (
    INTEGRATION_TESTERS_CHANNEL,
    PARCA,
    S3_APP,
    get_app_ip_address,
)

TEMPO = "tempo"
TEMPO_WORKER = "tempo-worker"

def deploy_monolithic_tempo_cluster(
    juju: Juju,
):
    """Deploy a tempo-monolithic cluster."""
    # worker and coordinator
    juju.deploy(
        "tempo-worker-k8s",
        app=TEMPO_WORKER,
        channel=INTEGRATION_TESTERS_CHANNEL,
        trust=True,
    )
    juju.deploy(
        "tempo-coordinator-k8s",
        app=TEMPO,
        channel=INTEGRATION_TESTERS_CHANNEL,
        trust=True,
    )
    juju.integrate(TEMPO, TEMPO_WORKER)

    # s3
    juju.deploy("seaweedfs-k8s", S3_APP, channel="edge")
    juju.integrate(f"{TEMPO}:s3", S3_APP)

    # wait for all active
    juju.wait(
        lambda status: jubilant.all_active(status, TEMPO, TEMPO_WORKER, S3_APP),
        timeout=2000,
        successes=6,
        delay=10,
    )


@pytest.mark.setup
def test_deploy_tempo_stack_monolithic(juju: Juju, parca_charm, parca_resources):
    juju.deploy(
        parca_charm,
        PARCA,
        resources=parca_resources,
        trust=True,
    )
    # deploy a tempo stack in monolithic mode
    deploy_monolithic_tempo_cluster(
        juju,
    )

    # send the charm and workload traces from `this stack` to the remote one
    juju.integrate(PARCA + ":charm-tracing", TEMPO + ":tracing")
    juju.integrate(PARCA + ":workload-tracing", TEMPO + ":tracing")
    juju.wait(
        lambda status: all(
            status.apps[app].is_active
            for app in [PARCA, TEMPO, TEMPO_WORKER]
        ),
        timeout=1000,
        successes=3,
        delay=10,
    )


def get_ingested_traces_tag_values(tempo_host, tls: bool, tag:str) -> Set[str]:
    """Fetch all ingested traces tags."""
    url = f"{'https' if tls else 'http'}://{tempo_host}:3200/api/search/tag/{tag}/values"
    req = requests.get(
        url,
        verify=False,
    )
    assert req.status_code == 200, req.reason
    tags = cast(List[str], req.json()["tagValues"])
    return set(tags)


@retry(stop=stop_after_attempt(3), wait=wait_fixed(10))
def test_verify_charm_tracing(juju: Juju):
    # adjust update-status interval to generate a charm tracing span faster
    juju.cli("model-config", "update-status-hook-interval=5s")

    services = get_ingested_traces_tag_values(
        get_app_ip_address(juju, TEMPO), tls=False, tag="service.name"
    )
    assert PARCA in services

    # adjust back to the default interval time
    juju.cli("model-config", "update-status-hook-interval=5m")


# @retry(stop=stop_after_attempt(3), wait=wait_fixed(10))
@pytest.mark.skip(reason="getting the UI isn't enough, we need to open a browser and click around.")
def test_verify_workload_tracing(juju: Juju):
    # we need to 'get' the UI for parca to generate a trace
    parca_ip = get_app_ip_address(juju, PARCA)
    requests.get(f"http://{parca_ip}:7994")

    process_exec_names = get_ingested_traces_tag_values(
        get_app_ip_address(juju, TEMPO), tls=False, tag="process.executable.name"
    )
    # this is a trace generated by parca workload
    assert "parca" in process_exec_names
