{
 "title": "Parca",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "At a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "High-level overview of core profiling system metrics: scrapes, profiles, and current ingestion."
   }
  },
  {
   "title": "Scraped targets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "parca_target_scrape_pool_sync_total"
    }
   ]
  },
  {
   "title": "Profile storage size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "frostdb_table_active_block_size"
    }
   ]
  },
  {
   "title": "Samples Appended",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(frostdb_table_rows_inserted_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])"
    }
   ]
  },
  { "title": "CPU / Memory / Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "Core nodes and Go metrics for the hosts. Look for high usage and abnormal spikes."
   }
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(juju_unit) (rate(process_cpu_seconds_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))"
    }
   ]
  },
  {
   "title": "Go heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes{}" }
   ]
  },
  {
   "title": "Resident memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}"
    }
   ]
  },
  {
   "title": "GCs (rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])"
    }
   ]
  },
  {
   "title": "OS threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "go_threads" }
   ]
  },
  {
   "title": "Writes from parca-agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "Overview of data from remote write interface used by [parca-agent](https://github.com/canonical/parca-agent-operator). Look for drops in regular ingestion levels / errors. "
   }
  },
  {
   "title": "Write Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"WriteRaw\",grpc_service=\"parca.profilestore.v1alpha1.ProfileStoreService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])) > 0",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Write Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Aborted|Unavailable|Internal|Unknown|Unimplemented|DataLoss\",grpc_method=\"WriteRaw\",grpc_service=\"parca.profilestore.v1alpha1.ProfileStoreService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Write Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"WriteRaw\",grpc_service=\"parca.profilestore.v1alpha1.ProfileStoreService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"WriteRaw\",grpc_service=\"parca.profilestore.v1alpha1.ProfileStoreService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"WriteRaw\",grpc_service=\"parca.profilestore.v1alpha1.ProfileStoreService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "options": {
    "content": "Overview of queries to Parca. Look for errors / sudden spikes."
   }
  },
  {
   "title": "QueryRange Requests",
   "type": "timeseries",
   "description": "These are the requests that query the overview metrics for profiles over a given time range.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"QueryRange\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])) > 0",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "QueryRange Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Aborted|Unavailable|Internal|Unknown|Unimplemented|DataLoss\",grpc_method=\"QueryRange\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "QueryRange Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"QueryRange\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"QueryRange\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"QueryRange\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Query Requests",
   "type": "timeseries",
   "description": "These are requests that show the actual profiles.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"Query\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])) > 0",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Aborted|Unavailable|Internal|Unknown|Unimplemented|DataLoss\",grpc_method=\"Query\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"Query\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"Query\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"Query\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Labels Requests",
   "type": "timeseries",
   "description": "These are the requests that return label names and values, usually used in UIs for label suggestions.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=~\"Labels|Values\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])) > 0",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Labels Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Aborted|Unavailable|Internal|Unknown|Unimplemented|DataLoss\",grpc_method=~\"Labels|Values\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Labels Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=~\"Labels|Values\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=~\"Labels|Values\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=~\"Labels|Values\",grpc_service=\"parca.query.v1alpha1.QueryService\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Storage / Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 66 },
   "options": {
    "content": "Overview of storage from compaction perspective. Look for drops in compaction or increase in data at lower levels."
   }
  },
  {
   "title": "Profile storage by compaction level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "frostdb_lsm_level_size_bytes", "legendFormat": "{{ level }}" }
   ]
  },
  {
   "title": "Compactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(frostdb_lsm_compactions_total[$__rate_interval])",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Compaction time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(frostdb_lsm_compaction_total_duration_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}