name: Pull Requests
on:
  pull_request:
    branches:
      - main
      - track/**

permissions:
  # Required for all workflows
  security-events: write
  # Only required for workflows in private repositories
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@3ab21836827cbc54bd7ea8e4e949300381ad658d # v2
    secrets: inherit
