name: Pull Requests
on:
  pull_request:
    branches:
      - main
      - track/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@b11dfdef528002f1765a87d3c7ab1a771f5bcbe0 # v2
    secrets: inherit
