name: Quality Gates

on:
  # Manual trigger
  workflow_dispatch:
  # Run the quality checks periodically
  # FIXME: adjust the frequency as needed once we have actual gates in place
  # schedule:
  #   - cron: "0 0 * * Tue"


jobs:
  quality-gates:
    name: Run quality gates
    uses: canonical/observability/.github/workflows/charm-quality-gates.yaml@3ab21836827cbc54bd7ea8e4e949300381ad658d # v2
    secrets: inherit