name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@ad88c000b208a68b2403aaada8f8b01141bdd18b # v1
    secrets: inherit
    with:
      default-track: 2
