name: Release to latest/edge

on:
  push:
    branches:
      - main

permissions:
  # Required for all workflows
  security-events: write
  # Only required for workflows in private repositories
  actions: read
  # Write permission needed for the reusable workflow to push git tags
  contents: write

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@3ab21836827cbc54bd7ea8e4e949300381ad658d # v2
    secrets: inherit
    with:
      default-track: dev
