name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@c13b2b9fedaf3e22861bd15ae4e53ad6506b5523 # v1
    secrets: inherit
    with:
      default-track: dev
