name: Tiobe TiCS Analysis

on:
    workflow_dispatch:
    schedule:
    - cron: "0 0 * * 1"  # Runs at midnight UTC every Monday

jobs:
    tics:
        name: TiCs
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@3ab21836827cbc54bd7ea8e4e949300381ad658d # v2
        secrets: inherit
